OK = 0x0
ERR_NO_SOCK = 0x1
 
MODE_BUTTON = 0x30
MODE_BUTTON_ACCELEROMETER = 0x31

SLEEP_DURATION = 5
SOCK_TIMEOUT_DURATION = 0.1

DEBUG = True

DISCOVER_DURATION = 5

ACCELEROMETER_ZERO = 0x80
ACCELEROMETER_PRECISION = 0x20

DISCONNECTED = 0x0
CONNECTED = 0x1

STATUS = { DISCONNECTED : "Disconnected",
           CONNECTED : "Connected",
           }
